### ISSUE TITLE
Automatic subscriptions

### ISSUE THREAD

**Issue by julianl890** [Azuriom/Plugin-Shop#31]
Is there a way to make a store package that the website remove a rank after 1 month ? So like renewal?

**Comment by MAXOUXAX** [comment]
Definitely needed!

**Comment by modcrafts** [comment]
When will support, we really need it!

**Comment by Ninatasia** [comment]
I also suggested something like this but more advanced (#130), to fit many more people and projects.

It was closed because this post was already created while very far away 🤷‍♀️
I hope it will be added one day because it is very useful for a game server. 😄

**Comment by MrMicky-FR** [comment]
> Azuriom is awesome. But it's focus is mainly minecraft. It is a bummer so I left it and used some other CMS. Awesome otherwise. But stuff like billing monthly is a must, since I VIP permissions you subscribe to not just buy.

Hi, I will be interested to know how Azuriom is Minecraft focused as almost all features are game-agnostic, feel free to write me on Discord (or open a separate issue) so we can improve the experience for other games. Thank you

**Comment by joti-prime** [comment]
Yes, will be good to create automatic subscriptions throught Paypal and stripe (so if people don't pay automatically cancels the role or the benefit) like tebex or other webs do.

**Comment by MrMicky-FR** [comment]
After lot of works, subscriptions are finally coming ! Currently this feature in is private beta before release, see the announcement on our [Discord server](https://azuriom.com/discord) for details and beta access 🚀

**Comment by crashzk** [comment]
An option for brands would be interesting if we want to block users from purchasing from this category if they already have a product from it.

Example, I create the VIP category and add the products there.
![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/a679c70f-99bb-4752-b707-ef2cfadccd6a)

In this VIP category, the user will only be able to purchase one product at a time and will only be able to purchase another when the product he purchased expires.

Same thing for selecting the product, if he has added Product 1 from the VIP category to the cart, he will only be able to add another product from the VIP category if he removes the one he already has in the cart, that is, adding several products to the cart from the same category will not it would be possible.

**Comment by crashzk** [comment]
> Currently the payments methods supported are Stripe (and now also Mollie and PayPal) and the website money, and the renewal period is configurable with the possibility of executing commands for the creation, renewal and expiry of a subscription. Other payment methods are planned based on feedbacks 🚀

**[MercadoPago Brasil](https://www.mercadopago.com.br/developers/en)**, are you thinking about being added to the payment methods?

He asked because I currently only use it, I have already implemented it in a project, I would like to know if they are thinking about including it officially in the payment method, or how it will work so that we can add our own payment methods to the subscription plan.

**Comment by MrMicky-FR** [comment]
Adding new payment methods is still not planned (especially not MercadoPago due to the lack of English resources), but the subscriptions are designed with modularity in mind so it’s perfectly possible to integrate new payment gateways for subscriptions

**Comment by MrMicky-FR** [comment]
Now available in version 1.2.0 of the shop 🚀
